repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        verbose: true
      - id: trailing-whitespace
        verbose: true
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
        verbose: true

# vim: set ts=2 sts=2 sw=2 et ai si sta:
